# Repository source|Path relative to HOME|Display name
wezterm/.wezterm.lua|.wezterm.lua|WezTerm
starship/starship.toml|.config/starship.toml|Starship
nvim|.config/nvim|Neovim
mise|.config/mise|mise
gitui/key_bindings.ron|.config/gitui/key_bindings.ron|gitui
zsh/.zshrc|.zshrc|zsh
git/config|.config/git/config|Git
