scan_timeout = 30
command_timeout = 500
add_newline = true

format = """
$directory$git_branch$git_status $golang $python $lua $cmd_duration
$character"""

[directory]
truncation_length = 4
truncation_symbol = "~/"
style = "fg:#768390"
format = "$path "

[git_branch]
symbol = " "
style = "fg:#539bf5"
format = "[$symbol$branch]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "fg:#c69026"

ahead = "[⇡${count}](fg:#539bf5)"
behind = "[⇣${count}](fg:#539bf5)"
diverged = "[⇕](fg:#986ee2)"

untracked = "[?${count}](fg:#c69026)"
modified = "[!${count}](fg:#c69026)"
staged = "[+${count}](fg:#57ab5a)"
renamed = "[»${count}](fg:#768390)"

conflicted = "[✖](fg:#f47067)"
deleted = "[✘${count}](fg:#f47067)"

stashed = "[${count}](fg:#768390)"

[golang]
symbol = " "
style = "fg:#539bf5"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "fg:#c69026"
format = "[$symbol$version]($style) "
python_binary = ["./.venv/bin/python", "python", "python3"]
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "Pipfile", "requirements.txt"]
detect_folders = [".venv"]

[lua]
symbol = " "
style = "fg:#539bf5"
format = "[$symbol$version]($style) "

[cmd_duration]
min_time = 1000
style = "fg:#636366"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](fg:#539bf5)"
error_symbol = "[❯](fg:#f47067)"
vimcmd_symbol = "[❮](fg:#c69026)"
