scan_timeout = 30
command_timeout = 500
add_newline = true

format = """
$time\
$username\
$directory\
$git_branch\
$git_status\
$git_metrics\
$golang\
$python\
$lua\
$cmd_duration
$character"""

[username]
show_always = false
style_user = "bold blue"
format = "[$user]($style) "

[directory]
truncation_length = 5
truncation_symbol = "…/"
style = "bold"
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
conflicted = "🏳"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
untracked = "?${count}"
stashed = "📦${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bold yellow"
format = "[$symbol$version]($style) "
python_binary = ["./.venv/bin/python", "python", "python3"]
detect_extensions = ["py"]
detect_files = ["pyproject.toml"]
detect_folders = [".venv"]

[lua]
symbol = " "
style = "bold blue"
format = '[$symbol$version(\($virtualenv\))]($style) '

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
format = "$symbol "

[custom.newline]
command = "echo ''"
when = "true"
format = "\n"

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "took [$duration]($style) "
show_milliseconds = true
show_notifications = false

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
disabled = false


[package]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[terraform]
disabled = true
