[tools]
"go:golang.org/x/tools/gopls" = "latest"           # doctor: gopls
lua-language-server = "latest"
"npm:pyright" = "latest"                           # doctor: pyright-langserver
"npm:@vtsls/language-server" = "latest"            # doctor: vtsls
"npm:vscode-langservers-extracted" = "latest"      # doctor: vscode-eslint-language-server vscode-html-language-server vscode-css-language-server vscode-json-language-server
"npm:@tailwindcss/language-server" = "latest"      # doctor: tailwindcss-language-server
rust-analyzer = "latest"
buf = "latest"
"github:coder3101/protols" = "latest"              # doctor: protols
"npm:yaml-language-server" = "latest"              # doctor: yaml-language-server
marksman = "latest"
"npm:dockerfile-language-server-nodejs" = "latest" # doctor: docker-langserver
"npm:bash-language-server" = "latest"              # doctor: bash-language-server
taplo = "latest"
